
DEFAULTS = {
    "CARE_IM_WRAPPER_META_VERIFY_TOKEN": "",
    "CARE_IM_WRAPPER_META_APP_SECRET": "",
    "CARE_IM_WRAPPER_META_ACCESS_TOKEN": "",
    "CARE_IM_WRAPPER_META_PHONE_NUMBER_ID": "",
}

REQUIRED_SETTINGS: set = set()
