# Generated by Django 6.0 on 2026-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone_number", models.CharField(max_length=20)),
                ("provider", models.CharField(default="whatsapp", max_length=20)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("patient", "Patient"), ("staff", "Staff")],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("snapshot_name", models.CharField(blank=True, default="", max_length=255)),
                ("snapshot_phone", models.CharField(blank=True, default="", max_length=20)),
                ("candidates", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("awaiting_yob", "Awaiting Year of Birth"),
                            ("ambiguous", "Ambiguous"),
                            ("authenticated", "Authenticated"),
                            ("cooldown", "Cooldown"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["phone_number", "provider"], name="care_im_wra_phone_n_ca3042_idx"),
                    models.Index(fields=["state"], name="care_im_wra_state_642e04_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("phone_number", "provider"), name="uq_session_phone_provider")
                ],
            },
        ),
    ]
