# Generated by Django 6.0 on 2026-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationsession",
            name="last_seen_at",
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="provider",
            field=models.CharField(choices=[("whatsapp", "WhatsApp")], default="whatsapp", max_length=20),
        ),
    ]
