# Generated by Django 6.0 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0002_remove_conversationsession_last_seen_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationsession",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("awaiting_yob", "Awaiting Year of Birth"),
                    ("ambiguous", "Ambiguous"),
                    ("authenticated", "Authenticated"),
                    ("cooldown", "Cooldown"),
                    ("awaiting_patient_search", "Awaiting Patient Search"),
                    ("selecting_patient", "Selecting Patient"),
                ],
                default="new",
                max_length=30,
            ),
        ),
    ]
