# Generated by Django 6.0 on 2026-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="active_patient_external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
