# Generated by Django 6.0 on 2026-07-07 06:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0004_add_conversationsession_active_patient_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("provider", models.CharField(choices=[("whatsapp", "WhatsApp")], default="whatsapp", max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utility"),
                            ("authentication", "Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("language_code", models.CharField(blank=True, max_length=10, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("variable_mapping", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "approval_status"], name="care_im_wra_provide_770e22_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationTrigger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("trigger_type", models.CharField(choices=[("signal", "Signal"), ("manual", "Manual")], max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [models.Index(fields=["trigger_type", "is_active"], name="care_im_wra_trigger_42503b_idx")],
            },
        ),
    ]
