# Generated by Django 6.0 on 2026-07-07 21:29

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0005_notificationtemplate_notificationtrigger"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                ("updated_by_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("variable_values", models.JSONField(blank=True, null=True)),
                ("related_object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "facility_organization_cache",
                    django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
                ),
                (
                    "related_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="care_im_wrapper.notificationtemplate"
                    ),
                ),
                (
                    "trigger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="care_im_wrapper.notificationtrigger"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("recipient_object_id", models.PositiveIntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                ("provider", models.CharField(choices=[("whatsapp", "WhatsApp")], default="whatsapp", max_length=20)),
                ("tracking_id", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("message_payload", models.JSONField(blank=True, null=True)),
                ("variable_overrides", models.JSONField(blank=True, null=True)),
                (
                    "latest_status",
                    models.CharField(
                        blank=True,
                        choices=[("sent", "Sent"), ("delivered", "Delivered"), ("read", "Read"), ("failed", "Failed")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="care_im_wrapper.notificationevent",
                    ),
                ),
                (
                    "recipient_content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("sent", "Sent"), ("delivered", "Delivered"), ("read", "Read"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_events",
                        to="care_im_wrapper.notificationrecipient",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notificationevent",
            index=models.Index(
                fields=["related_object_content_type", "related_object_id"], name="care_im_wra_related_32cade_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(fields=["tracking_id"], name="care_im_wra_trackin_5cc002_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(
                fields=["recipient_content_type", "recipient_object_id"], name="care_im_wra_recipie_56225b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(fields=["event", "latest_status"], name="care_im_wra_event_i_30e203_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationstatus",
            index=models.Index(fields=["recipient", "state"], name="care_im_wra_recipie_caa32f_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationstatus",
            index=models.Index(fields=["created_date"], name="care_im_wra_created_e95a0f_idx"),
        ),
    ]
