# Generated by Django 6.0 on 2026-07-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0007_seed_appointment_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtemplate",
            name="parameter_format",
            field=models.CharField(
                choices=[("positional", "Positional ({{1}}, {{2}}, ...)"), ("named", "Named ({{patient_name}}, ...)")],
                default="positional",
                max_length=20,
            ),
        ),
    ]
