# Generated by Django 6.0 on 2026-07-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0009_notificationtrigger_template_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationevent",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationevent",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationrecipient",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationrecipient",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationtrigger",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationtrigger",
            name="modified_date",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
