# Generated by Django 6.0 on 2026-07-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0010_alter_notificationevent_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtrigger",
            name="context_slug",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
