# Generated by Django 6.0 on 2026-07-17 21:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0013_seed_document_ready_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ("deleted", models.BooleanField(db_index=True, default=False)),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "object_kind",
                    models.CharField(
                        choices=[("report_upload", "Report Upload"), ("file_upload", "File Upload")], max_length=20
                    ),
                ),
                ("object_external_id", models.UUIDField()),
                ("document_type", models.CharField(max_length=100)),
                ("patient_external_id", models.UUIDField()),
                ("provider", models.CharField(choices=[("whatsapp", "WhatsApp")], default="whatsapp", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("access_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["patient_external_id", "object_kind", "object_external_id"],
                        name="care_im_wra_patient_d62b97_idx",
                    )
                ],
            },
        ),
    ]
