# Generated by Django 6.0 on 2026-07-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0015_conversationsession_selecting_document_state"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrecipient",
            name="dispatch_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="notificationrecipient",
            index=models.Index(fields=["latest_status", "dispatch_started_at"], name="care_im_wra_latest__3459bd_idx"),
        ),
    ]
