# Generated by Django 6.0 on 2026-07-26 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0016_notificationrecipient_dispatch_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="last_active_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
