# Generated by Django 6.0 on 2026-08-06 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0022_notificationevent_facility_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversationsession",
            name="care_im_wra_phone_n_ca3042_idx",
        ),
    ]
