# Generated by Django 6.0 on 2026-08-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0024_remove_notificationevent_facility_organization_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="data_record_offsets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="data_records_shown",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
