# Generated by Django 6.0 on 2026-08-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0025_conversationsession_data_record_offsets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationtrigger",
            name="trigger_type",
            field=models.CharField(choices=[("signal", "Signal")], max_length=20),
        ),
    ]
