# Generated by Django 6.0 on 2026-08-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_im_wrapper", "0029_invoice_triggers_use_invoice_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentlink",
            name="object_kind",
            field=models.CharField(
                choices=[
                    ("report_upload", "Report Upload"),
                    ("file_upload", "File Upload"),
                    ("diagnostic_report", "Diagnostic Report"),
                ],
                max_length=20,
            ),
        ),
    ]
